        /etc/nginx/sites-available/default

#La configuration pour les deux Proxy

# Configuration du serveur de proxy
server {
        listen 81 default_server;
        listen [::]:81 default_server;

        server_name _;

        # 1. Configuration globale du WAF ModSecurity
        modsecurity on;
        modsecurity_rules_file /etc/modsecurity/modsecurity.conf;

        # En-têmes standards indispensables pour le Reverse Proxy
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 2. Aiguillage vers le Frontend (Le site Web - Port 80)
        location / {
                proxy_pass http://10.10.2.10:80;
        }

        # 3. Aiguillage vers le Backend (L'API FastAPI - Port 5000)
        # Toutes les requêtes HTTP qui commencent par /api/ iront ici
        location /api/ {
                proxy_pass http://10.10.2.10:5000;
        }
}