          /etc/modsecurity/modsecurity.conf
#La configuration sur les deux Proxy

# --- Configuration de Base ModSecurity v3 ---
# Activer le moteur en mode blocage (On) et non détection seule
SecRuleEngine On

# Gestion du corps des requêtes (Request Body)
SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject

# Gestion du corps des réponses (Response Body)
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml
SecResponseBodyLimit 5242880
SecResponseBodyLimitAction ProcessPartial

# Fichiers temporaires et de debug
SecTmpDir /tmp/
SecDataDir /tmp/

# Configuration des LOGS (Très important pour débugger tes blocages)
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABCFHJK
SecAuditLogType Serial
SecAuditLog /var/log/nginx/modsec_audit.log

# Paramètres d'arguments
SecArgumentSeparator &

# Statut du moteur de règles
SecStatusEngine On

# Configuration locale des règles OWASP CRS
Include /etc/modsecurity/crs-setup.conf
Include /etc/modsecurity/crs-rules/*.conf