               /etc/squid/squid.conf
#La configuration pour les deux Proxy

# Configuration DNS
dns_nameservers 8.8.8.8 1.1.1.1
dns_v4_first on

# Liaison explicite
http_port 8080

# Définition de notre réseau interne global (VLANs)
acl localnet src 10.10.0.0/16

# Définition des ports valides pour les dépôts APT (HTTP et HTTPS)
acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 443         # https
acl CONNECT method CONNECT

# Règles de sécurité strictes
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# Autoriser CONNECT pour HTTPS
http_access allow CONNECT SSL_ports

# --- DROITS D'ACCÈS ---
# Autoriser le réseau local et la machine locale
http_access allow localnet
http_access allow localhost

# Tout le reste est bloqué
http_access deny all

# Cache pour APT
refresh_pattern -i \.(deb|udeb)$  129600 100% 129600
refresh_pattern -i \.tar\.gz$     129600 100% 129600
refresh_pattern .                  0       20%  4320